### ISSUE TITLE
clone on windows fails because of folder names ending with period

### ISSUE THREAD

**Issue by acdoerin** [scanoss/purl2cpe#12]
The project cannot be cloned on a windows system. 
Here is the log:

Receiving objects: 100% (74000/74000), 579.43 MiB | 6.40 MiB/s, done.
Resolving deltas: 100% (6009/6009), done.
error: invalid path 'data/arj_software_inc./unarj/cpes.yml'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

git did not exit cleanly (exit code 128) (117781 ms @ 06/10/2023 14:04:40)

My work is not dependent on this but we found this in a related project.

**Comment by scanossmining** [comment]
@acdoerin we've added a new filter to ignore records for malformed cpes, so the one you reported is no longer in the dataset. When it will be fixed in the NVD, it will show up in our dataset too.
