### ISSUE TITLE
purl spells wrong

### ISSUE THREAD

**Issue by emiyadavid** [scanoss/purl2cpe#19]
Does the value of purl spell wrong? **_pkg:gituhb/eldy/awstats_**

maybe '**_pkg:github/eldy/awstats_**' is correct

![image](https://github.com/scanoss/purl2cpe/assets/23526061/35131f0f-ea29-4829-b7a5-05a48701e23d)

**Comment by emiyadavid** [comment]
The issue is fixed. But there is still exists some other purls has the same problem, such as 'pkg:gituhb/wayned/rsync'. Hope to check.

**Comment by scanossmining** [comment]
@emiyadavid thank you for pointing this out. we will search for the other ones and fix those too!

**Comment by emiyadavid** [comment]
好的，我已收到！
