### ISSUE TITLE
purls do not appear to be validated before being added

### ISSUE THREAD

**Issue by gitgitwhat** [scanoss/purl2cpe#5]
For example, look at purl2cpe/data/libav/libav/purls.yml

`pkggithub/libav/libav` is not correct.  That shouldn't pass the most basic check.

I've processed the entire repo and there are thousands of invalid purls.  Not sure how they are derived but some simple quality check using https://github.com/package-url/purl-spec would be very helpful.

**Comment by scanossmining** [comment]
Hi @gitgitwhat , thank you for reporting this. We've cleaned up the wrongly formatted purls and we'll add more checks in order to avoid these from showing up. Would you share with us the full list of invalid purls you detected, in order for us to investigate further?

**Comment by perezale** [comment]
<div>Agent Alejandro Perez unlinked Freshdesk ticket <a href="https://scanoss.freshdesk.com/a/tickets/1400">1400</a> from this issue.</div>
